import { Question } from "@/types"

export const questionBank: Question[] = [
  // ── General Security Concepts (12%) ── 14 questions
  {
    id: "gsc_001", type: "mcq", domain: "General Security Concepts",
    text: "A security analyst is reviewing security controls and notices that the organization uses automatic account lockout after five failed login attempts. Which type of security control is this?",
    answers: [
      { id: "a", text: "Detective", isCorrect: false },
      { id: "b", text: "Corrective", isCorrect: false },
      { id: "c", text: "Preventive", isCorrect: true },
      { id: "d", text: "Compensating", isCorrect: false },
    ],
    explanation: "Account lockout is a preventive control because it stops attacks (such as brute force) before they succeed. Detective controls identify events after they occur, and corrective controls restore systems after an incident.",
  },
  {
    id: "gsc_002", type: "mcq", domain: "General Security Concepts",
    text: "An organization wants to implement a security model where no user or device is trusted by default, regardless of network location. Every access request must be verified. Which security model does this describe?",
    answers: [
      { id: "a", text: "Defense in depth", isCorrect: false },
      { id: "b", text: "Zero trust", isCorrect: true },
      { id: "c", text: "Least privilege", isCorrect: false },
      { id: "d", text: "Need to know", isCorrect: false },
    ],
    explanation: "Zero trust eliminates implicit trust based on network location. Every user, device, and connection must be continuously verified. Defense in depth uses layered controls but does not eliminate implicit trust.",
  },
  {
    id: "gsc_003", type: "mcq", domain: "General Security Concepts",
    text: "A company stores customer data and wants to ensure only authorized personnel can read it, that it has not been modified without authorization, and that it remains accessible. Which framework represents these requirements?",
    answers: [
      { id: "a", text: "AAA", isCorrect: false },
      { id: "b", text: "CIA triad", isCorrect: true },
      { id: "c", text: "Zero trust", isCorrect: false },
      { id: "d", text: "DAD", isCorrect: false },
    ],
    explanation: "The CIA triad maps directly: Confidentiality (authorized read access), Integrity (no unauthorized modification), and Availability (accessible when needed). AAA covers authentication, authorization, and accounting.",
  },
  {
    id: "gsc_004", type: "mcq", domain: "General Security Concepts",
    text: "A security engineer deploys asymmetric encryption for initial key exchange and symmetric encryption for ongoing data transfer. Why is this the recommended approach?",
    answers: [
      { id: "a", text: "Asymmetric is more secure than symmetric", isCorrect: false },
      { id: "b", text: "Symmetric cannot be used for key exchange", isCorrect: false },
      { id: "c", text: "Asymmetric is too slow for bulk data", isCorrect: true },
      { id: "d", text: "Symmetric does not require a shared secret", isCorrect: false },
    ],
    explanation: "Asymmetric encryption is significantly slower than symmetric encryption. It is used for key exchange because it allows secure establishment of a shared secret. Once established, the faster symmetric algorithm handles bulk data transfer.",
  },
  {
    id: "gsc_005", type: "mcq", domain: "General Security Concepts",
    text: "A security engineer is implementing access controls for a classified database. Users should only access data at or below their clearance level. Which access control model is this?",
    answers: [
      { id: "a", text: "Discretionary Access Control (DAC)", isCorrect: false },
      { id: "b", text: "Role-Based Access Control (RBAC)", isCorrect: false },
      { id: "c", text: "Mandatory Access Control (MAC)", isCorrect: true },
      { id: "d", text: "Attribute-Based Access Control (ABAC)", isCorrect: false },
    ],
    explanation: "MAC assigns access based on security labels and classification levels set by a central authority. Users cannot modify their own access. This model is used in government environments where clearance determines access.",
  },
  {
    id: "gsc_006", type: "mcq", domain: "General Security Concepts",
    text: "Which of the following BEST describes the purpose of a digital certificate?",
    answers: [
      { id: "a", text: "Encrypts data in transit between systems", isCorrect: false },
      { id: "b", text: "Binds a public key to an identity", isCorrect: true },
      { id: "c", text: "Creates a hash of data for integrity", isCorrect: false },
      { id: "d", text: "Provides authentication via shared secret", isCorrect: false },
    ],
    explanation: "A digital certificate is issued by a Certificate Authority and cryptographically binds a public key to an identity. It proves you are communicating with the legitimate entity, not an impersonator.",
  },
  {
    id: "gsc_007", type: "mcq", domain: "General Security Concepts",
    text: "A systems administrator wants to make it impossible for a user to deny having performed an action. Which principle is the administrator trying to enforce?",
    answers: [
      { id: "a", text: "Non-repudiation", isCorrect: true },
      { id: "b", text: "Adaptive identity", isCorrect: false },
      { id: "c", text: "Security zones", isCorrect: false },
      { id: "d", text: "Deception and disruption", isCorrect: false },
    ],
    explanation: "Non-repudiation ensures that a user cannot deny having performed an action. It is typically implemented through digital signatures and audit logs that provide proof of the action and the identity of the actor.",
  },
  {
    id: "gsc_008", type: "mcq", domain: "General Security Concepts",
    text: "Which security principle ensures that users are granted only the access necessary to perform their job functions?",
    answers: [
      { id: "a", text: "Separation of duties", isCorrect: false },
      { id: "b", text: "Least privilege", isCorrect: true },
      { id: "c", text: "Defense in depth", isCorrect: false },
      { id: "d", text: "Zero trust", isCorrect: false },
    ],
    explanation: "Least privilege ensures users have only the minimum permissions needed. Separation of duties splits critical tasks across multiple people. Defense in depth uses layered controls.",
  },
  {
    id: "gsc_009", type: "mcq", domain: "General Security Concepts",
    text: "An organization requires employees to use a smart card and a PIN to access the data center. Which of the following BEST describes this control?",
    answers: [
      { id: "a", text: "Multi-factor authentication", isCorrect: true },
      { id: "b", text: "Single sign-on", isCorrect: false },
      { id: "c", text: "Biometric authentication", isCorrect: false },
      { id: "d", text: "Attribute-based access control", isCorrect: false },
    ],
    explanation: "A smart card (something you have) plus a PIN (something you know) constitutes MFA because it uses factors from two different categories. SSO reduces credential count, and biometrics use something you are.",
  },
  {
    id: "gsc_010", type: "mcq", domain: "General Security Concepts",
    text: "A security architect is designing a defense strategy using firewalls at the perimeter, host-based IDS on servers, and endpoint protection on workstations. Which principle does this illustrate?",
    answers: [
      { id: "a", text: "Least privilege", isCorrect: false },
      { id: "b", text: "Defense in depth", isCorrect: true },
      { id: "c", text: "Zero trust", isCorrect: false },
      { id: "d", text: "Separation of duties", isCorrect: false },
    ],
    explanation: "Defense in depth uses multiple layers of security controls so that if one layer fails, others still provide protection. Least privilege limits permissions, and separation of duties divides responsibilities.",
  },
  {
    id: "gsc_011", type: "mcq", domain: "General Security Concepts",
    text: "Which type of security control decreases the likelihood of a cybersecurity breach occurring?",
    answers: [
      { id: "a", text: "Corrective", isCorrect: false },
      { id: "b", text: "Detective", isCorrect: false },
      { id: "c", text: "Preventive", isCorrect: true },
      { id: "d", text: "Compensating", isCorrect: false },
    ],
    explanation: "Preventive controls act before or during an attack to stop it. Corrective controls restore after an incident, and detective controls identify events that have already occurred.",
  },
  {
    id: "gsc_012", type: "mcq", domain: "General Security Concepts",
    text: "A company installs security cameras throughout its office building to discourage unauthorized access. What type of security control is this?",
    answers: [
      { id: "a", text: "Preventive", isCorrect: false },
      { id: "b", text: "Detective", isCorrect: false },
      { id: "c", text: "Deterrent", isCorrect: true },
      { id: "d", text: "Corrective", isCorrect: false },
    ],
    explanation: "Security cameras are a deterrent control because they discourage people from attempting unauthorized access by increasing the perceived risk of being caught. They also serve a detective function.",
  },
  {
    id: "gsc_013", type: "mcq", domain: "General Security Concepts",
    text: "An organization requires all employees to complete annual security awareness training. Which category of control does this represent?",
    answers: [
      { id: "a", text: "Technical", isCorrect: false },
      { id: "b", text: "Physical", isCorrect: false },
      { id: "c", text: "Administrative", isCorrect: true },
      { id: "d", text: "Compensating", isCorrect: false },
    ],
    explanation: "Security awareness training is an administrative (also called managerial) control. Administrative controls include policies, training, and procedures that govern behavior.",
  },
  {
    id: "gsc_014", type: "mcq", domain: "General Security Concepts",
    text: "A data owner needs to grant access to a file but can only delegate that authority to specific users. Which access control model is in use?",
    answers: [
      { id: "a", text: "Mandatory Access Control (MAC)", isCorrect: false },
      { id: "b", text: "Discretionary Access Control (DAC)", isCorrect: true },
      { id: "c", text: "Role-Based Access Control (RBAC)", isCorrect: false },
      { id: "d", text: "Attribute-Based Access Control (ABAC)", isCorrect: false },
    ],
    explanation: "DAC allows the owner of a resource to determine who can access it and delegate that authority. MAC uses system-enforced labels, RBAC uses roles, and ABAC uses attributes.",
  },

  // ── Threats, Vulnerabilities, and Mitigations (22%) ── 26 questions
  {
    id: "tvm_001", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An employee receives an email that appears to come from the CEO requesting an urgent wire transfer. The email domain is subtly misspelled. Which attack type is this?",
    answers: [
      { id: "a", text: "Vishing", isCorrect: false },
      { id: "b", text: "Spear phishing", isCorrect: false },
      { id: "c", text: "Whaling", isCorrect: true },
      { id: "d", text: "Smishing", isCorrect: false },
    ],
    explanation: "Whaling is a targeted phishing attack directed at senior executives. Spear phishing targets specific individuals but is not necessarily focused on executives. Vishing uses voice calls, and smishing uses SMS.",
  },
  {
    id: "tvm_002", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A penetration tester discovers a web application vulnerable to SQL injection. Which mitigation MOST directly addresses this vulnerability?",
    answers: [
      { id: "a", text: "Implement a WAF", isCorrect: false },
      { id: "b", text: "Use parameterized queries", isCorrect: true },
      { id: "c", text: "Enable HTTPS on the server", isCorrect: false },
      { id: "d", text: "Restrict input length", isCorrect: false },
    ],
    explanation: "Parameterized queries treat user input as data rather than executable code, preventing SQL injection at the source. A WAF is a secondary defense that can be bypassed, and input length restrictions can be circumvented.",
  },
  {
    id: "tvm_003", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An attacker intercepts communication between a user and a web server, reads the traffic, and forwards it without either party knowing. Which attack is this?",
    answers: [
      { id: "a", text: "Replay attack", isCorrect: false },
      { id: "b", text: "Man-in-the-middle", isCorrect: true },
      { id: "c", text: "Session hijacking", isCorrect: false },
      { id: "d", text: "SSL stripping", isCorrect: false },
    ],
    explanation: "A man-in-the-middle attack positions the attacker between two parties to intercept and potentially modify traffic. Replay attacks capture and replay tokens. SSL stripping is a specific MitM technique.",
  },
  {
    id: "tvm_004", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A user reports their computer is running slowly, unknown programs appear in the task manager, and the machine generates unexpected outbound traffic. Which type of malware is MOST likely responsible?",
    answers: [
      { id: "a", text: "Ransomware", isCorrect: false },
      { id: "b", text: "Rootkit", isCorrect: false },
      { id: "c", text: "Botnet agent", isCorrect: true },
      { id: "d", text: "Adware", isCorrect: false },
    ],
    explanation: "The combination of slow performance, unexpected processes, and outbound traffic indicates a botnet agent communicating with a C2 server. Ransomware encrypts files and displays a ransom demand. Rootkits conceal their presence.",
  },
  {
    id: "tvm_005", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A software vendor releases a patch for a critical vulnerability. An organization requires 30 days of testing before deployment. Three days after the patch release, attackers exploit the unpatched vulnerability. Which term describes this scenario?",
    answers: [
      { id: "a", text: "Zero-day exploit", isCorrect: false },
      { id: "b", text: "Window of vulnerability", isCorrect: true },
      { id: "c", text: "Legacy system risk", isCorrect: false },
      { id: "d", text: "Supply chain attack", isCorrect: false },
    ],
    explanation: "The window of vulnerability is the period between discovery or disclosure of a vulnerability and deployment of a patch. Zero-day exploits target vulnerabilities before a patch exists.",
  },
  {
    id: "tvm_006", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "Which of the following BEST describes a supply chain attack?",
    answers: [
      { id: "a", text: "Exploiting an OS vulnerability", isCorrect: false },
      { id: "b", text: "Compromising a third-party vendor to target customers", isCorrect: true },
      { id: "c", text: "Social engineering a logistics company", isCorrect: false },
      { id: "d", text: "Intercepting software updates in transit", isCorrect: false },
    ],
    explanation: "Supply chain attacks compromise a trusted vendor or software provider to reach their customers. The SolarWinds attack is the most prominent example of this method.",
  },
  {
    id: "tvm_007", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An organization discovers an attacker has been exfiltrating data over six months using encrypted channels that blend into normal traffic. Which term BEST describes this attack?",
    answers: [
      { id: "a", text: "Insider threat", isCorrect: false },
      { id: "b", text: "Advanced Persistent Threat", isCorrect: true },
      { id: "c", text: "Distributed Denial of Service", isCorrect: false },
      { id: "d", text: "Privilege escalation", isCorrect: false },
    ],
    explanation: "An APT is characterized by long-term, stealthy access with slow data exfiltration. The use of encrypted channels to blend with normal traffic is a hallmark APT evasion technique.",
  },
  {
    id: "tvm_008", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A business development team reports files missing from the database and login screens showing a lock symbol demanding payment. Which attack is the company facing?",
    answers: [
      { id: "a", text: "Rootkit", isCorrect: false },
      { id: "b", text: "Ransomware", isCorrect: true },
      { id: "c", text: "Spyware", isCorrect: false },
      { id: "d", text: "Bloatware", isCorrect: false },
    ],
    explanation: "Ransomware encrypts files and displays a ransom demand. Rootkits hide malicious activity, spyware steals information, and bloatware is unwanted pre-installed software.",
  },
  {
    id: "tvm_009", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "Which threat actor is MOST likely to use common hacking tools found on the internet to compromise an organization's web server?",
    answers: [
      { id: "a", text: "Organized crime", isCorrect: false },
      { id: "b", text: "Insider threat", isCorrect: false },
      { id: "c", text: "Unskilled attacker", isCorrect: true },
      { id: "d", text: "Nation-state", isCorrect: false },
    ],
    explanation: "Unskilled attackers (also called script kiddies) use readily available tools and scripts without deep technical understanding. Organized crime and nation-states use more sophisticated techniques.",
  },
  {
    id: "tvm_010", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An attacker captures wireless traffic and uses software to crack the pre-shared key offline. Which attack method is this?",
    answers: [
      { id: "a", text: "Evil twin", isCorrect: false },
      { id: "b", text: "Brute-force", isCorrect: false },
      { id: "c", text: "Dictionary attack", isCorrect: true },
      { id: "d", text: "Deauthentication", isCorrect: false },
    ],
    explanation: "A dictionary attack uses a list of common passwords against captured hashes. Brute-force tries every possible combination. Evil twin uses a rogue AP, and deauthentication disconnects clients.",
  },
  {
    id: "tvm_011", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A user receives a phone call from someone claiming to be from IT asking for their password to install an update. Which social engineering principle is the attacker using?",
    answers: [
      { id: "a", text: "Scarcity", isCorrect: false },
      { id: "b", text: "Authority", isCorrect: true },
      { id: "c", text: "Social proof", isCorrect: false },
      { id: "d", text: "Urgency", isCorrect: false },
    ],
    explanation: "The attacker impersonates an authority figure (IT department) to gain compliance. Urgency may also be present, but the core manipulation is authority through impersonation of a trusted role.",
  },
  {
    id: "tvm_012", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A security analyst notices repeated failed login attempts from a single IP address targeting multiple user accounts. Which type of attack is occurring?",
    answers: [
      { id: "a", text: "Password spraying", isCorrect: true },
      { id: "b", text: "Credential stuffing", isCorrect: false },
      { id: "c", text: "Brute-force", isCorrect: false },
      { id: "d", text: "Keylogging", isCorrect: false },
    ],
    explanation: "Password spraying tries a few common passwords against many accounts, avoiding account lockout. Credential stuffing uses breached credentials, and brute-force tries many passwords against a single account.",
  },
  {
    id: "tvm_013", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An attacker sends a fraudulent text message claiming the recipient won a gift card and must click a link to claim it. Which attack type is this?",
    answers: [
      { id: "a", text: "Vishing", isCorrect: false },
      { id: "b", text: "Phishing", isCorrect: false },
      { id: "c", text: "Smishing", isCorrect: true },
      { id: "d", text: "Whaling", isCorrect: false },
    ],
    explanation: "Smishing is phishing via SMS/text messages. Vishing uses voice calls, whaling targets executives, and phishing typically refers to email-based attacks.",
  },
  {
    id: "tvm_014", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "Which of the following is a characteristic of a cross-site scripting (XSS) attack?",
    answers: [
      { id: "a", text: "Malicious code injected into a database query", isCorrect: false },
      { id: "b", text: "Malicious script injected into a trusted website", isCorrect: true },
      { id: "c", text: "Excessive data sent to overflow a buffer", isCorrect: false },
      { id: "d", text: "Fake certificate presented to a browser", isCorrect: false },
    ],
    explanation: "XSS injects malicious client-side scripts into web pages viewed by other users. SQL injection targets databases, buffer overflows exploit memory boundaries, and fake certificates are a PKI attack.",
  },
  {
    id: "tvm_015", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A security team wants to identify vulnerabilities in their network without triggering alerts or sending packets. Which method should they use?",
    answers: [
      { id: "a", text: "Active scanning", isCorrect: false },
      { id: "b", text: "Passive reconnaissance", isCorrect: true },
      { id: "c", text: "Penetration testing", isCorrect: false },
      { id: "d", text: "Vulnerability scanning", isCorrect: false },
    ],
    explanation: "Passive reconnaissance gathers information without directly interacting with the target, such as analyzing publicly available data or monitoring network traffic. Active methods send packets that can be detected.",
  },
  {
    id: "tvm_016", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A company discovers that an employee's credentials were used to access a system from a foreign country at the same time the employee was in the office. Which attack MOST likely occurred?",
    answers: [
      { id: "a", text: "Pass-the-hash", isCorrect: false },
      { id: "b", text: "Credential theft", isCorrect: true },
      { id: "c", text: "Replay attack", isCorrect: false },
      { id: "d", text: "On-path attack", isCorrect: false },
    ],
    explanation: "The credentials were stolen and used from a different location. Pass-the-hash uses hashed credentials without knowing the password. Replay attacks capture and replay authentication tokens.",
  },
  {
    id: "tvm_017", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An attacker compromises a website and injects code that redirects visitors to a malicious site. Which type of attack is this?",
    answers: [
      { id: "a", text: "Phishing", isCorrect: false },
      { id: "b", text: "DNS poisoning", isCorrect: false },
      { id: "c", text: "Watering hole attack", isCorrect: true },
      { id: "d", text: "Typosquatting", isCorrect: false },
    ],
    explanation: "A watering hole attack compromises a site that the target group frequently visits. Phishing uses fraudulent messages, DNS poisoning corrupts DNS resolution, and typosquatting uses misspelled domains.",
  },
  {
    id: "tvm_018", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "Which vulnerability class involves an attacker sending more data than a program's buffer can hold?",
    answers: [
      { id: "a", text: "SQL injection", isCorrect: false },
      { id: "b", text: "Buffer overflow", isCorrect: true },
      { id: "c", text: "Cross-site scripting", isCorrect: false },
      { id: "d", text: "Integer overflow", isCorrect: false },
    ],
    explanation: "A buffer overflow occurs when a program writes more data to a buffer than it can hold, potentially allowing code execution. SQL injection targets databases, XSS targets browsers, and integer overflow affects numeric calculations.",
  },
  {
    id: "tvm_019", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A security analyst needs to test the organization's security controls by simulating an attack. Which activity should the analyst perform?",
    answers: [
      { id: "a", text: "Vulnerability scan", isCorrect: false },
      { id: "b", text: "Penetration test", isCorrect: true },
      { id: "c", text: "Security audit", isCorrect: false },
      { id: "d", text: "Risk assessment", isCorrect: false },
    ],
    explanation: "A penetration test simulates real attacks to identify exploitable vulnerabilities. Vulnerability scans identify potential vulnerabilities without exploitation. Audits review compliance, and risk assessments evaluate overall risk.",
  },
  {
    id: "tvm_020", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "Which of the following is NOT a typical characteristic of a zero-day vulnerability?",
    answers: [
      { id: "a", text: "No vendor patch exists", isCorrect: false },
      { id: "b", text: "It is publicly disclosed before a fix", isCorrect: false },
      { id: "c", text: "It has been known for over a year", isCorrect: true },
      { id: "d", text: "It can be exploited before discovery", isCorrect: false },
    ],
    explanation: "A zero-day vulnerability is one for which no patch exists at the time of disclosure. If it has been known for over a year, it is no longer zero-day — it becomes a known vulnerability.",
  },
  {
    id: "tvm_021", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An attacker uses a replay attack to gain unauthorized access. Which control BEST mitigates replay attacks?",
    answers: [
      { id: "a", text: "Strong password policy", isCorrect: false },
      { id: "b", text: "Session tokens with timestamps", isCorrect: true },
      { id: "c", text: "Network segmentation", isCorrect: false },
      { id: "d", text: "Antivirus software", isCorrect: false },
    ],
    explanation: "Session tokens with timestamps and sequence numbers prevent replay because captured tokens expire or are rejected as out of sequence. Strong passwords do not prevent token capture and replay.",
  },
  {
    id: "tvm_022", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A security team identifies that an attacker is using a known vulnerability in an unpatched application. Which type of threat actor is MOST likely responsible for this attack?",
    answers: [
      { id: "a", text: "Nation-state", isCorrect: false },
      { id: "b", text: "Unskilled attacker", isCorrect: true },
      { id: "c", text: "Organized crime", isCorrect: false },
      { id: "d", text: "Insider threat", isCorrect: false },
    ],
    explanation: "Unskilled attackers typically exploit known vulnerabilities using publicly available tools. Nation-states and organized crime groups often develop custom exploits or use more sophisticated methods.",
  },
  {
    id: "tvm_023", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "A malware sample connects to a C2 server, receives instructions, and then downloads additional payloads. Which malware category does this describe?",
    answers: [
      { id: "a", text: "Trojan", isCorrect: false },
      { id: "b", text: "Worm", isCorrect: false },
      { id: "c", text: "Remote Access Trojan", isCorrect: true },
      { id: "d", text: "Ransomware", isCorrect: false },
    ],
    explanation: "A Remote Access Trojan (RAT) provides an attacker with remote control of the infected system. Trojans disguise themselves as legitimate software, while RATs specifically provide backdoor access.",
  },
  {
    id: "tvm_024", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "Which attack exploits the trust relationship between a user's browser and a third-party site by sending forged requests?",
    answers: [
      { id: "a", text: "Cross-site request forgery", isCorrect: true },
      { id: "b", text: "Cross-site scripting", isCorrect: false },
      { id: "c", text: "SQL injection", isCorrect: false },
      { id: "d", text: "Server-side request forgery", isCorrect: false },
    ],
    explanation: "CSRF forges requests from an authenticated user's browser to a target site. XSS injects scripts, SQLi targets databases, and SSRF targets server-side resources.",
  },
  {
    id: "tvm_025", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "An organization's web server is overwhelmed with traffic from many compromised devices. Which attack type is occurring?",
    answers: [
      { id: "a", text: "DDoS", isCorrect: true },
      { id: "b", text: "DNS poisoning", isCorrect: false },
      { id: "c", text: "ARP spoofing", isCorrect: false },
      { id: "d", text: "Session hijacking", isCorrect: false },
    ],
    explanation: "A distributed denial-of-service (DDoS) attack uses multiple compromised systems to flood a target with traffic. DNS poisoning corrupts DNS data, ARP spoofing maps attacker MAC to a legitimate IP.",
  },
  {
    id: "tvm_026", type: "mcq", domain: "Threats, Vulnerabilities, and Mitigations",
    text: "Which of the following is the BEST defense against a brute-force attack on user passwords?",
    answers: [
      { id: "a", text: "Complex password policy", isCorrect: false },
      { id: "b", text: "Account lockout after failed attempts", isCorrect: true },
      { id: "c", text: "Password expiration every 30 days", isCorrect: false },
      { id: "d", text: "Password history requirement", isCorrect: false },
    ],
    explanation: "Account lockout directly prevents brute-force by blocking further attempts after a threshold. Complex passwords and expiration slow the attack but do not stop it once it begins.",
  },

  // ── Security Architecture (18%) ── 22 questions
  {
    id: "sac_001", type: "mcq", domain: "Security Architecture",
    text: "A company is migrating workloads to a public cloud. The security team needs to understand which responsibilities belong to the provider and which belong to the organization. Which model defines this division?",
    answers: [
      { id: "a", text: "Defense in depth", isCorrect: false },
      { id: "b", text: "Shared responsibility model", isCorrect: true },
      { id: "c", text: "Zero trust architecture", isCorrect: false },
      { id: "d", text: "Infrastructure as code", isCorrect: false },
    ],
    explanation: "The shared responsibility model defines that the cloud provider secures the infrastructure while the customer secures their data, applications, and access within the cloud.",
  },
  {
    id: "sac_002", type: "mcq", domain: "Security Architecture",
    text: "An organization wants to prevent lateral movement after a system compromise. Which network architecture approach BEST addresses this?",
    answers: [
      { id: "a", text: "DMZ placement", isCorrect: false },
      { id: "b", text: "Network segmentation with VLANs", isCorrect: true },
      { id: "c", text: "Perimeter firewall", isCorrect: false },
      { id: "d", text: "Network address translation", isCorrect: false },
    ],
    explanation: "Network segmentation divides the network into separate zones with controlled traffic flow. If an attacker compromises one segment, controls between segments limit lateral movement.",
  },
  {
    id: "sac_003", type: "mcq", domain: "Security Architecture",
    text: "A financial company processes cardholder data and wants to reduce PCI DSS compliance scope. Which approach is MOST effective?",
    answers: [
      { id: "a", text: "Encrypt all cardholder data at rest", isCorrect: false },
      { id: "b", text: "Tokenization to replace cardholder data", isCorrect: true },
      { id: "c", text: "Deploy a WAF", isCorrect: false },
      { id: "d", text: "Network segmentation", isCorrect: false },
    ],
    explanation: "Tokenization replaces actual cardholder data with non-sensitive tokens. Systems that see only tokens can be removed from PCI scope. Encryption protects data but does not eliminate scope.",
  },
  {
    id: "sac_004", type: "mcq", domain: "Security Architecture",
    text: "A company wants security integrated at every stage of development, not just before release. Which approach does this describe?",
    answers: [
      { id: "a", text: "Penetration testing", isCorrect: false },
      { id: "b", text: "SIEM", isCorrect: false },
      { id: "c", text: "DevSecOps", isCorrect: true },
      { id: "d", text: "Vulnerability scanning", isCorrect: false },
    ],
    explanation: "DevSecOps integrates security practices into every SDLC stage. Penetration testing and vulnerability scanning are point-in-time assessments, not continuous integration of security.",
  },
  {
    id: "sac_005", type: "mcq", domain: "Security Architecture",
    text: "An organization needs a critical application to remain available even if one data center fails. Which architecture BEST meets this requirement?",
    answers: [
      { id: "a", text: "Load balancing within one data center", isCorrect: false },
      { id: "b", text: "Active-active across two geographic regions", isCorrect: true },
      { id: "c", text: "Daily backup to offsite storage", isCorrect: false },
      { id: "d", text: "Redundant servers in the same data center", isCorrect: false },
    ],
    explanation: "Active-active across geographically separated regions ensures that a complete facility failure does not disrupt service. Backup allows recovery after downtime, not continuous availability.",
  },
  {
    id: "sac_006", type: "mcq", domain: "Security Architecture",
    text: "Which cloud service model gives the customer the most control over the operating system and applications?",
    answers: [
      { id: "a", text: "Software as a Service (SaaS)", isCorrect: false },
      { id: "b", text: "Platform as a Service (PaaS)", isCorrect: false },
      { id: "c", text: "Infrastructure as a Service (IaaS)", isCorrect: true },
      { id: "d", text: "Function as a Service (FaaS)", isCorrect: false },
    ],
    explanation: "IaaS provides virtualized computing resources where the customer manages the OS, middleware, and applications. SaaS provides ready-to-use software, and PaaS provides a platform for application development.",
  },
  {
    id: "sac_007", type: "mcq", domain: "Security Architecture",
    text: "A security architect is designing a DMZ. Which systems should be placed in the DMZ?",
    answers: [
      { id: "a", text: "Internal database servers", isCorrect: false },
      { id: "b", text: "Public-facing web servers", isCorrect: true },
      { id: "c", text: "Domain controllers", isCorrect: false },
      { id: "d", text: "File servers", isCorrect: false },
    ],
    explanation: "A DMZ hosts systems that are accessible from the internet, such as web, email, and DNS servers. Internal resources like databases and domain controllers should be on the internal network with restricted DMZ access.",
  },
  {
    id: "sac_008", type: "mcq", domain: "Security Architecture",
    text: "Which type of firewall operates at the application layer and can inspect the contents of traffic?",
    answers: [
      { id: "a", text: "Packet filter", isCorrect: false },
      { id: "b", text: "Stateful firewall", isCorrect: false },
      { id: "c", text: "Next-generation firewall", isCorrect: true },
      { id: "d", text: "Stateless firewall", isCorrect: false },
    ],
    explanation: "Next-generation firewalls (NGFW) combine traditional firewall functions with application-layer inspection, intrusion prevention, and other advanced features beyond packet and stateful inspection.",
  },
  {
    id: "sac_009", type: "mcq", domain: "Security Architecture",
    text: "An organization uses a VPN to connect remote employees to the corporate network. What does the VPN primarily protect?",
    answers: [
      { id: "a", text: "Data at rest", isCorrect: false },
      { id: "b", text: "Data in transit", isCorrect: true },
      { id: "c", text: "Data in use", isCorrect: false },
      { id: "d", text: "Data sovereignty", isCorrect: false },
    ],
    explanation: "A VPN encrypts traffic between the remote user and the corporate network, protecting data while it is in transit over potentially untrusted networks.",
  },
  {
    id: "sac_010", type: "mcq", domain: "Security Architecture",
    text: "Which technology monitors network traffic for suspicious patterns but does NOT automatically block traffic?",
    answers: [
      { id: "a", text: "Intrusion Prevention System (IPS)", isCorrect: false },
      { id: "b", text: "Intrusion Detection System (IDS)", isCorrect: true },
      { id: "c", text: "Next-generation firewall (NGFW)", isCorrect: false },
      { id: "d", text: "Web application firewall (WAF)", isCorrect: false },
    ],
    explanation: "An IDS monitors and alerts but does not take blocking action. An IPS both detects and blocks. This distinction is frequently tested on the exam.",
  },
  {
    id: "sac_011", type: "mcq", domain: "Security Architecture",
    text: "An organization wants to ensure that if a laptop is stolen, the data on it remains unreadable. Which control BEST addresses this?",
    answers: [
      { id: "a", text: "Strong power-on password", isCorrect: false },
      { id: "b", text: "Full-disk encryption", isCorrect: true },
      { id: "c", text: "Remote wipe capability", isCorrect: false },
      { id: "d", text: "Asset tracking software", isCorrect: false },
    ],
    explanation: "Full-disk encryption protects data at rest even if the device is physically stolen. A password can be bypassed, remote wipe requires network connectivity, and tracking does not protect data.",
  },
  {
    id: "sac_012", type: "mcq", domain: "Security Architecture",
    text: "Which of the following is the BEST example of a detective control?",
    answers: [
      { id: "a", text: "Firewall rule blocking traffic", isCorrect: false },
      { id: "b", text: "SIEM alert on unusual login patterns", isCorrect: true },
      { id: "c", text: "Backup restoration after data loss", isCorrect: false },
      { id: "d", text: "Security awareness training", isCorrect: false },
    ],
    explanation: "A SIEM alert detects patterns that indicate security events after they occur. Firewall rules are preventive, backups are corrective, and training is administrative.",
  },
  {
    id: "sac_013", type: "mcq", domain: "Security Architecture",
    text: "An organization uses redundant power supplies and UPS systems for its servers. Which type of control is this?",
    answers: [
      { id: "a", text: "Preventive", isCorrect: false },
      { id: "b", text: "Detective", isCorrect: false },
      { id: "c", text: "Compensating", isCorrect: false },
      { id: "d", text: "Corrective", isCorrect: true },
    ],
    explanation: "Redundant power supplies and UPS are corrective controls because they allow systems to continue operating or recover after a power failure. They do not prevent power failures.",
  },
  {
    id: "sac_014", type: "mcq", domain: "Security Architecture",
    text: "Which backup method copies only files changed since the last full backup and resets the archive bit?",
    answers: [
      { id: "a", text: "Full backup", isCorrect: false },
      { id: "b", text: "Differential backup", isCorrect: false },
      { id: "c", text: "Incremental backup", isCorrect: true },
      { id: "d", text: "Snapshot", isCorrect: false },
    ],
    explanation: "Incremental backups copy files changed since the last backup (full or incremental) and reset the archive bit. Differential copies files changed since the last full backup without resetting the bit.",
  },
  {
    id: "sac_015", type: "mcq", domain: "Security Architecture",
    text: "A company wants to standardize security configurations across all endpoints. Which approach is BEST?",
    answers: [
      { id: "a", text: "Manual configuration by administrators", isCorrect: false },
      { id: "b", text: "Security baselines and automated enforcement", isCorrect: true },
      { id: "c", text: "Annual security audits", isCorrect: false },
      { id: "d", text: "User self-configuration", isCorrect: false },
    ],
    explanation: "Security baselines provide standardized configurations that are enforced automatically, ensuring consistency. Manual configuration is error-prone, audits are point-in-time, and user configuration is unreliable.",
  },
  {
    id: "sac_016", type: "mcq", domain: "Security Architecture",
    text: "Which of the following is a characteristic of containerization in application deployment?",
    answers: [
      { id: "a", text: "Each application runs on a separate hypervisor", isCorrect: false },
      { id: "b", text: "Applications share the host OS kernel", isCorrect: true },
      { id: "c", text: "Containers require a full OS per instance", isCorrect: false },
      { id: "d", text: "Containers are less efficient than VMs", isCorrect: false },
    ],
    explanation: "Containers share the host OS kernel, making them lighter than VMs which each run a separate OS. Containers provide isolation at the application level rather than the hardware level.",
  },
  {
    id: "sac_017", type: "mcq", domain: "Security Architecture",
    text: "An organization deploys an MDM solution that creates a separate encrypted work container on employee-owned phones. Corporate data can be remotely wiped without affecting personal data. Which concept is illustrated?",
    answers: [
      { id: "a", text: "Sandboxing", isCorrect: true },
      { id: "b", text: "Network segmentation", isCorrect: false },
      { id: "c", text: "Data classification", isCorrect: false },
      { id: "d", text: "Separation of duties", isCorrect: false },
    ],
    explanation: "Sandboxing isolates corporate applications and data from personal data on the same device. This enables remote wipe of corporate data without affecting personal information.",
  },
  {
    id: "sac_018", type: "mcq", domain: "Security Architecture",
    text: "Which network device is designed to attract and trap attackers to study their methods?",
    answers: [
      { id: "a", text: "Honeypot", isCorrect: true },
      { id: "b", text: "Load balancer", isCorrect: false },
      { id: "c", text: "Proxy server", isCorrect: false },
      { id: "d", text: "VPN concentrator", isCorrect: false },
    ],
    explanation: "A honeypot is a decoy system designed to appear as a legitimate target to attract attackers. It allows security teams to study attack methods without risking production systems.",
  },
  {
    id: "sac_019", type: "mcq", domain: "Security Architecture",
    text: "Which protocol provides secure remote access to a router's command-line interface?",
    answers: [
      { id: "a", text: "Telnet", isCorrect: false },
      { id: "b", text: "SSH", isCorrect: true },
      { id: "c", text: "FTP", isCorrect: false },
      { id: "d", text: "SNMP", isCorrect: false },
    ],
    explanation: "SSH (Secure Shell) provides encrypted remote access to network device CLIs. Telnet sends data in plaintext, FTP is for file transfers, and SNMP is for network management.",
  },
  {
    id: "sac_020", type: "mcq", domain: "Security Architecture",
    text: "An organization needs to allow web traffic from the internet to its web server in the DMZ. Which firewall rule should be created?",
    answers: [
      { id: "a", text: "Allow all traffic from DMZ to internet", isCorrect: false },
      { id: "b", text: "Allow inbound port 80 and 443 to the web server", isCorrect: true },
      { id: "c", text: "Allow all traffic from internet to DMZ", isCorrect: false },
      { id: "d", text: "Block all inbound traffic", isCorrect: false },
    ],
    explanation: "The firewall should allow only HTTP (80) and HTTPS (443) traffic from the internet to the web server in the DMZ, following the principle of least access.",
  },
  {
    id: "sac_021", type: "mcq", domain: "Security Architecture",
    text: "Which technology combines multiple security functions into a single cloud-delivered platform?",
    answers: [
      { id: "a", text: "SIEM", isCorrect: false },
      { id: "b", text: "SASE", isCorrect: true },
      { id: "c", text: "IDS", isCorrect: false },
      { id: "d", text: "DLP", isCorrect: false },
    ],
    explanation: "Secure Access Service Edge (SASE) combines networking and security functions (SWG, CASB, ZTNA, etc.) into a single cloud-delivered service. SIEM focuses on log analysis.",
  },
  {
    id: "sac_022", type: "mcq", domain: "Security Architecture",
    text: "A security architect needs to ensure that a database server is only accessible from the application server, not directly from users. Which control BEST achieves this?",
    answers: [
      { id: "a", text: "Application-layer firewall rules", isCorrect: true },
      { id: "b", text: "Database encryption", isCorrect: false },
      { id: "c", text: "Strong database passwords", isCorrect: false },
      { id: "d", text: "Database activity monitoring", isCorrect: false },
    ],
    explanation: "Firewall rules that restrict database server access to only the application server's IP address enforce network-level access control. Encryption and passwords protect data but do not restrict access paths.",
  },

  // ── Security Operations (28%) ── 34 questions
  {
    id: "sop_001", type: "mcq", domain: "Security Operations",
    text: "A security analyst receives an alert that a privileged account authenticated from two different countries within 30 minutes. Which detection technique is this?",
    answers: [
      { id: "a", text: "Signature-based detection", isCorrect: false },
      { id: "b", text: "Heuristic analysis", isCorrect: false },
      { id: "c", text: "Impossible travel detection", isCorrect: true },
      { id: "d", text: "Behavioral baselining", isCorrect: false },
    ],
    explanation: "Impossible travel detection flags authentications from geographically distant locations within a time frame that makes physical travel impossible. This is a common SIEM use case.",
  },
  {
    id: "sop_002", type: "mcq", domain: "Security Operations",
    text: "During incident response, an analyst finds a suspicious executable. What should the analyst do FIRST to determine if it is known malware?",
    answers: [
      { id: "a", text: "Execute it in a production environment", isCorrect: false },
      { id: "b", text: "Calculate its hash and check threat databases", isCorrect: true },
      { id: "c", text: "Decompile the file", isCorrect: false },
      { id: "d", text: "Submit it to a sandbox", isCorrect: false },
    ],
    explanation: "A hash comparison against known malware databases (like VirusTotal) is the fastest and safest first step. It requires no execution and can immediately identify known malware.",
  },
  {
    id: "sop_003", type: "mcq", domain: "Security Operations",
    text: "A SOC receives a high volume of alerts on Monday morning. What should the team prioritize?",
    answers: [
      { id: "a", text: "Investigate in chronological order", isCorrect: false },
      { id: "b", text: "Triage by severity and business impact", isCorrect: true },
      { id: "c", text: "Dismiss all low-severity alerts", isCorrect: false },
      { id: "d", text: "Escalate all alerts to senior analysts", isCorrect: false },
    ],
    explanation: "Alert triage prioritizes based on severity and potential business impact to address the most critical threats first. Working chronologically or dismissing alerts risks missing critical incidents.",
  },
  {
    id: "sop_004", type: "mcq", domain: "Security Operations",
    text: "An analyst creates a SIEM rule that alerts when more than ten failed logins occur on the same account within five minutes, followed by a successful login. Which rule type is this?",
    answers: [
      { id: "a", text: "Signature-based", isCorrect: false },
      { id: "b", text: "Correlation rule", isCorrect: true },
      { id: "c", text: "Threshold rule", isCorrect: false },
      { id: "d", text: "Anomaly detection", isCorrect: false },
    ],
    explanation: "A correlation rule combines multiple event types and timing relationships. A threshold rule triggers on a single event exceeding a count. This rule correlates failed attempts followed by success.",
  },
  {
    id: "sop_005", type: "mcq", domain: "Security Operations",
    text: "A server is communicating with an unauthorized external IP on port 443. What should the administrator do FIRST per incident response procedures?",
    answers: [
      { id: "a", text: "Shut down the server immediately", isCorrect: false },
      { id: "b", text: "Block the IP at the firewall", isCorrect: false },
      { id: "c", text: "Document and notify the IR team", isCorrect: true },
      { id: "d", text: "Run a full antivirus scan", isCorrect: false },
    ],
    explanation: "The first step is identification and notification. Taking action without notifying the IR team can destroy evidence. The IR team coordinates containment after assessment.",
  },
  {
    id: "sop_006", type: "mcq", domain: "Security Operations",
    text: "A forensic investigator creates a bit-for-bit copy of a hard drive and stores the original in an evidence bag with a chain of custody form. Why is this necessary?",
    answers: [
      { id: "a", text: "To back up the drive in case it fails", isCorrect: false },
      { id: "b", text: "To preserve evidence integrity and admissibility", isCorrect: true },
      { id: "c", text: "To speed up the analysis process", isCorrect: false },
      { id: "d", text: "To comply with data retention policies", isCorrect: false },
    ],
    explanation: "Working from a forensic copy preserves the original evidence unmodified. Chain of custody documents prove evidence has not been tampered with, which is required for legal admissibility.",
  },
  {
    id: "sop_007", type: "mcq", domain: "Security Operations",
    text: "Which of the following is the FIRST phase of the incident response lifecycle?",
    answers: [
      { id: "a", text: "Containment", isCorrect: false },
      { id: "b", text: "Eradication", isCorrect: false },
      { id: "c", text: "Preparation", isCorrect: true },
      { id: "d", text: "Recovery", isCorrect: false },
    ],
    explanation: "The incident response lifecycle begins with preparation, which includes creating policies, training teams, and acquiring tools. Containment, eradication, and recovery occur after identification.",
  },
  {
    id: "sop_008", type: "mcq", domain: "Security Operations",
    text: "A company wants to detect anomalous behavior on their network and generate alerts. Which tool is BEST suited for this purpose?",
    answers: [
      { id: "a", text: "SIEM", isCorrect: true },
      { id: "b", text: "WAF", isCorrect: false },
      { id: "c", text: "DLP", isCorrect: false },
      { id: "d", text: "NAC", isCorrect: false },
    ],
    explanation: "A Security Information and Event Management (SIEM) system aggregates logs from multiple sources and uses correlation rules to detect anomalies and generate alerts.",
  },
  {
    id: "sop_009", type: "mcq", domain: "Security Operations",
    text: "Which of the following is the BEST example of a corrective control in security operations?",
    answers: [
      { id: "a", text: "Firewall blocking malicious traffic", isCorrect: false },
      { id: "b", text: "Restoring data from backup after ransomware", isCorrect: true },
      { id: "c", text: "SIEM alert on suspicious activity", isCorrect: false },
      { id: "d", text: "Security awareness training", isCorrect: false },
    ],
    explanation: "Restoring from backup after an incident is a corrective control because it fixes damage after the fact. Blocking traffic is preventive, SIEM alerts are detective, and training is administrative.",
  },
  {
    id: "sop_010", type: "mcq", domain: "Security Operations",
    text: "An organization implements MFA for all administrative accounts. Which authentication factors would be used in an MFA implementation?",
    answers: [
      { id: "a", text: "Password and security question", isCorrect: false },
      { id: "b", text: "Smart card and PIN", isCorrect: true },
      { id: "c", text: "Username and password", isCorrect: false },
      { id: "d", text: "Two security questions", isCorrect: false },
    ],
    explanation: "MFA requires factors from at least two categories. A smart card (something you have) plus PIN (something you know) qualifies. Password plus security question is still in the knowledge category.",
  },
  {
    id: "sop_011", type: "mcq", domain: "Security Operations",
    text: "A company wants to prevent sensitive data from being sent via email. Which security solution is BEST suited?",
    answers: [
      { id: "a", text: "SIEM", isCorrect: false },
      { id: "b", text: "DLP", isCorrect: true },
      { id: "c", text: "IPS", isCorrect: false },
      { id: "d", text: "WAF", isCorrect: false },
    ],
    explanation: "Data Loss Prevention (DLP) solutions monitor and control data transfers to prevent unauthorized disclosure. SIEM analyzes logs, IPS blocks network attacks, and WAF protects web applications.",
  },
  {
    id: "sop_012", type: "mcq", domain: "Security Operations",
    text: "What is the PRIMARY purpose of a playbook in security operations?",
    answers: [
      { id: "a", text: "Document network configurations", isCorrect: false },
      { id: "b", text: "Provide step-by-step incident response procedures", isCorrect: true },
      { id: "c", text: "Track employee training completion", isCorrect: false },
      { id: "d", text: "Record security policy violations", isCorrect: false },
    ],
    explanation: "A playbook provides standardized, step-by-step procedures for responding to specific types of security incidents, ensuring consistent and effective response.",
  },
  {
    id: "sop_013", type: "mcq", domain: "Security Operations",
    text: "Which of the following is a key function of a SOAR platform?",
    answers: [
      { id: "a", text: "Analyzing network traffic patterns", isCorrect: false },
      { id: "b", text: "Automating incident response workflows", isCorrect: true },
      { id: "c", text: "Blocking malicious websites", isCorrect: false },
      { id: "d", text: "Encrypting sensitive data", isCorrect: false },
    ],
    explanation: "SOAR (Security Orchestration, Automation, and Response) platforms automate incident response workflows by orchestrating tools and executing predefined response actions.",
  },
  {
    id: "sop_014", type: "mcq", domain: "Security Operations",
    text: "A security analyst needs to identify all devices connected to the network before allowing them access. Which technology is BEST for this?",
    answers: [
      { id: "a", text: "NAC", isCorrect: true },
      { id: "b", text: "IDS", isCorrect: false },
      { id: "c", text: "VPN", isCorrect: false },
      { id: "d", text: "DLP", isCorrect: false },
    ],
    explanation: "Network Access Control (NAC) checks devices for compliance and authorization before granting network access. IDS detects threats, VPN provides encrypted tunnels, and DLP prevents data loss.",
  },
  {
    id: "sop_015", type: "mcq", domain: "Security Operations",
    text: "During which phase of incident response does the team focus on removing the threat from the environment?",
    answers: [
      { id: "a", text: "Detection", isCorrect: false },
      { id: "b", text: "Containment", isCorrect: false },
      { id: "c", text: "Eradication", isCorrect: true },
      { id: "d", text: "Recovery", isCorrect: false },
    ],
    explanation: "Eradication is the phase where the root cause is removed, malware is cleaned, and vulnerabilities are patched. Containment isolates the threat, and recovery restores normal operations.",
  },
  {
    id: "sop_016", type: "mcq", domain: "Security Operations",
    text: "An organization wants to ensure that system changes are reviewed and approved before implementation. Which process should they follow?",
    answers: [
      { id: "a", text: "Vulnerability management", isCorrect: false },
      { id: "b", text: "Change management", isCorrect: true },
      { id: "c", text: "Incident management", isCorrect: false },
      { id: "d", text: "Configuration management", isCorrect: false },
    ],
    explanation: "Change management ensures that changes to systems are formally reviewed, approved, tested, and documented before implementation. Configuration management tracks the state of systems.",
  },
  {
    id: "sop_017", type: "mcq", domain: "Security Operations",
    text: "A security analyst notices a user account has been locked due to excessive failed login attempts from multiple locations. Which containment action should be taken FIRST?",
    answers: [
      { id: "a", text: "Reset the user's password", isCorrect: true },
      { id: "b", text: "Delete the user account", isCorrect: false },
      { id: "c", text: "Ignore the alert as a false positive", isCorrect: false },
      { id: "d", text: "Unlock the account", isCorrect: false },
    ],
    explanation: "Resetting the password prevents further unauthorized access using the compromised credentials. Deleting the account is too extreme without investigation, and unlocking would allow further attacks.",
  },
  {
    id: "sop_018", type: "mcq", domain: "Security Operations",
    text: "Which log source would be MOST valuable for investigating a potential data breach?",
    answers: [
      { id: "a", text: "Firewall logs", isCorrect: false },
      { id: "b", text: "Database access logs", isCorrect: true },
      { id: "c", text: "Printer logs", isCorrect: false },
      { id: "d", text: "Temperature sensor logs", isCorrect: false },
    ],
    explanation: "Database access logs show who accessed what data and when, making them most relevant for a data breach investigation. Firewall logs show network traffic but not data access.",
  },
  {
    id: "sop_019", type: "mcq", domain: "Security Operations",
    text: "A company needs to ensure that only authorized software can run on company workstations. Which security control should they implement?",
    answers: [
      { id: "a", text: "Antivirus software", isCorrect: false },
      { id: "b", text: "Application allowlisting", isCorrect: true },
      { id: "c", text: "Host firewall", isCorrect: false },
      { id: "d", text: "Patch management", isCorrect: false },
    ],
    explanation: "Application allowlisting permits only approved software to execute. Antivirus detects known malware but does not prevent unauthorized software from running. Host firewalls control network access.",
  },
  {
    id: "sop_020", type: "mcq", domain: "Security Operations",
    text: "During a forensic investigation, which of the following should be documented FIRST?",
    answers: [
      { id: "a", text: "The attacker's identity", isCorrect: false },
      { id: "b", text: "Chain of custody", isCorrect: true },
      { id: "c", text: "Root cause analysis", isCorrect: false },
      { id: "d", text: "Remediation steps", isCorrect: false },
    ],
    explanation: "Chain of custody must be documented from the moment evidence is collected to preserve admissibility. Attacker identity, root cause, and remediation come later in the process.",
  },
  {
    id: "sop_021", type: "mcq", domain: "Security Operations",
    text: "A company discovers that a terminated employee still has access to the network. Which control should have prevented this?",
    answers: [
      { id: "a", text: "Stronger password policy", isCorrect: false },
      { id: "b", text: "Account provisioning and deprovisioning process", isCorrect: true },
      { id: "c", text: "MFA for all accounts", isCorrect: false },
      { id: "d", text: "Network segmentation", isCorrect: false },
    ],
    explanation: "A proper account deprovisioning process ensures accounts are disabled or removed when employees leave. Passwords, MFA, and segmentation do not address account lifecycle management.",
  },
  {
    id: "sop_022", type: "mcq", domain: "Security Operations",
    text: "A SOC analyst sees a spike in outbound traffic from an internal server at 3 AM. Which is the BEST next step?",
    answers: [
      { id: "a", text: "Block all outbound traffic from the server", isCorrect: false },
      { id: "b", text: "Investigate the traffic pattern and destination", isCorrect: true },
      { id: "c", text: "Reboot the server", isCorrect: false },
      { id: "d", text: "Ignore it as backup activity", isCorrect: false },
    ],
    explanation: "The analyst should investigate before taking action. Unusual outbound traffic at off-hours could indicate data exfiltration. Blocking or rebooting without investigation could destroy evidence.",
  },
  {
    id: "sop_023", type: "mcq", domain: "Security Operations",
    text: "Which tool is BEST for identifying vulnerabilities in a network without authenticating to target systems?",
    answers: [
      { id: "a", text: "Authenticated vulnerability scan", isCorrect: false },
      { id: "b", text: "Unauthenticated vulnerability scan", isCorrect: true },
      { id: "c", text: "Penetration test", isCorrect: false },
      { id: "d", text: "Security audit", isCorrect: false },
    ],
    explanation: "An unauthenticated scan identifies vulnerabilities visible from the network without credentials, simulating an external attacker. Authenticated scans provide deeper visibility but require credentials.",
  },
  {
    id: "sop_024", type: "mcq", domain: "Security Operations",
    text: "A company wants to automatically block traffic from known malicious IP addresses. Which tool is BEST suited?",
    answers: [
      { id: "a", text: "Intrusion Detection System (IDS)", isCorrect: false },
      { id: "b", text: "Intrusion Prevention System (IPS)", isCorrect: true },
      { id: "c", text: "Security Information and Event Management (SIEM)", isCorrect: false },
      { id: "d", text: "Vulnerability scanner", isCorrect: false },
    ],
    explanation: "An IPS can automatically block traffic based on signatures including known malicious IPs. IDS only alerts, SIEM aggregates logs, and vulnerability scanners identify weaknesses.",
  },
  {
    id: "sop_025", type: "mcq", domain: "Security Operations",
    text: "An incident responder needs to preserve evidence from a running system. Which action BEST preserves the evidence?",
    answers: [
      { id: "a", text: "Pull the power cord immediately", isCorrect: false },
      { id: "b", text: "Capture a memory image before shutting down", isCorrect: true },
      { id: "c", text: "Delete suspicious files", isCorrect: false },
      { id: "d", text: "Run antivirus software", isCorrect: false },
    ],
    explanation: "Capturing a memory image preserves volatile evidence (running processes, network connections) that would be lost on shutdown. Pulling the power destroys volatile data.",
  },
  {
    id: "sop_026", type: "mcq", domain: "Security Operations",
    text: "Which of the following BEST describes the principle of least privilege for service accounts?",
    answers: [
      { id: "a", text: "The account should have admin rights for troubleshooting", isCorrect: false },
      { id: "b", text: "The account should have only the permissions required", isCorrect: true },
      { id: "c", text: "The account should use the same password as user accounts", isCorrect: false },
      { id: "d", text: "The account should be a domain admin", isCorrect: false },
    ],
    explanation: "Least privilege for service accounts means granting only the specific permissions needed for the service to function. Over-privileged service accounts are a common security risk.",
  },
  {
    id: "sop_027", type: "mcq", domain: "Security Operations",
    text: "A company needs to monitor all traffic entering and leaving the network. Which device should be placed at the network boundary?",
    answers: [
      { id: "a", text: "Load balancer", isCorrect: false },
      { id: "b", text: "Firewall", isCorrect: true },
      { id: "c", text: "Switch", isCorrect: false },
      { id: "d", text: "Access point", isCorrect: false },
    ],
    explanation: "A firewall is placed at the network boundary to inspect and control traffic entering and leaving the network. Load balancers distribute traffic, switches connect local devices, and APs provide wireless access.",
  },
  {
    id: "sop_028", type: "mcq", domain: "Security Operations",
    text: "An organization is notified that employee credentials were found on the dark web. Which action should be taken FIRST?",
    answers: [
      { id: "a", text: "Ignore it if no breach is confirmed", isCorrect: false },
      { id: "b", text: "Reset affected credentials and investigate", isCorrect: true },
      { id: "c", text: "Notify law enforcement", isCorrect: false },
      { id: "d", text: "Disable all user accounts", isCorrect: false },
    ],
    explanation: "Resetting affected credentials prevents their use by attackers, followed by investigation to determine how they were compromised. Law enforcement notification may follow but is not the first step.",
  },
  {
    id: "sop_029", type: "mcq", domain: "Security Operations",
    text: "Which of the following is the PRIMARY goal of the containment phase in incident response?",
    answers: [
      { id: "a", text: "Identify the root cause", isCorrect: false },
      { id: "b", text: "Prevent further damage", isCorrect: true },
      { id: "c", text: "Restore normal operations", isCorrect: false },
      { id: "d", text: "Document lessons learned", isCorrect: false },
    ],
    explanation: "Containment focuses on stopping the incident from causing additional damage. Root cause analysis happens during eradication, restoration during recovery, and documentation during lessons learned.",
  },
  {
    id: "sop_030", type: "mcq", domain: "Security Operations",
    text: "An organization wants to ensure that suspicious files can be analyzed in a safe, isolated environment. Which technique should they use?",
    answers: [
      { id: "a", text: "Static analysis", isCorrect: false },
      { id: "b", text: "Sandboxing", isCorrect: true },
      { id: "c", text: "Code signing", isCorrect: false },
      { id: "d", text: "Patch management", isCorrect: false },
    ],
    explanation: "Sandboxing executes suspicious files in an isolated environment to observe their behavior without risking production systems. Static analysis examines code without execution.",
  },
  {
    id: "sop_031", type: "mcq", domain: "Security Operations",
    text: "A security analyst is reviewing logs and sees repeated authentication failures for a service account followed by a successful authentication. What does this pattern suggest?",
    answers: [
      { id: "a", text: "The service account password was changed", isCorrect: false },
      { id: "b", text: "A brute-force attack succeeded", isCorrect: true },
      { id: "c", text: "The account was locked out", isCorrect: false },
      { id: "d", text: "The service was restarted", isCorrect: false },
    ],
    explanation: "Repeated failures followed by success indicates a successful brute-force or password guessing attack. Password changes typically show a single failure before success, not repeated failures.",
  },
  {
    id: "sop_032", type: "mcq", domain: "Security Operations",
    text: "Which of the following is the BEST data source for identifying the spread of malware across the network?",
    answers: [
      { id: "a", text: "DNS logs", isCorrect: false },
      { id: "b", text: "Netflow data", isCorrect: true },
      { id: "c", text: "DHCP logs", isCorrect: false },
      { id: "d", text: "Syslog from servers", isCorrect: false },
    ],
    explanation: "Netflow data shows network connections between IP addresses, making it ideal for tracking lateral movement. DNS logs show name resolution, DHCP shows IP assignment, and syslog shows system events.",
  },
  {
    id: "sop_033", type: "mcq", domain: "Security Operations",
    text: "A company wants to detect insider threats by identifying users accessing data outside of normal patterns. Which approach is MOST effective?",
    answers: [
      { id: "a", text: "Reviewing access logs manually", isCorrect: false },
      { id: "b", text: "User and Entity Behavior Analytics (UEBA)", isCorrect: true },
      { id: "c", text: "Random password changes", isCorrect: false },
      { id: "d", text: "Strict firewall rules", isCorrect: false },
    ],
    explanation: "UEBA establishes baseline behavior patterns and alerts on anomalies. Manual review does not scale, and password changes or firewall rules do not detect behavioral anomalies.",
  },
  {
    id: "sop_034", type: "mcq", domain: "Security Operations",
    text: "An organization needs to ensure that security patches are applied to systems in a timely manner. Which process is MOST important for achieving this?",
    answers: [
      { id: "a", text: "Asset inventory and patch management", isCorrect: true },
      { id: "b", text: "Annual security training", isCorrect: false },
      { id: "c", text: "Penetration testing", isCorrect: false },
      { id: "d", text: "Physical access controls", isCorrect: false },
    ],
    explanation: "Asset inventory identifies what needs patching, and patch management automates the deployment. Without knowing what systems exist, timely patching is impossible.",
  },

  // ── Security Program Management and Oversight (20%) ── 24 questions
  {
    id: "spm_001", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A company assesses the risk of a potential incident. The estimated financial impact is $500,000 with a 20% annual probability. What is the Annual Loss Expectancy (ALE)?",
    answers: [
      { id: "a", text: "$500,000", isCorrect: false },
      { id: "b", text: "$100,000", isCorrect: true },
      { id: "c", text: "$2,500,000", isCorrect: false },
      { id: "d", text: "$250,000", isCorrect: false },
    ],
    explanation: "ALE = SLE × ARO. SLE is $500,000, ARO is 0.20 (20%). $500,000 × 0.20 = $100,000. This calculation helps compare incident cost against control cost.",
  },
  {
    id: "spm_002", type: "mcq", domain: "Security Program Management and Oversight",
    text: "An organization wants to transfer the financial risk of a data breach to a third party. Which risk response strategy is this?",
    answers: [
      { id: "a", text: "Risk avoidance", isCorrect: false },
      { id: "b", text: "Risk mitigation", isCorrect: false },
      { id: "c", text: "Risk transference", isCorrect: true },
      { id: "d", text: "Risk acceptance", isCorrect: false },
    ],
    explanation: "Risk transference moves the financial consequences to a third party, typically through cyber insurance. Avoidance eliminates the activity, mitigation reduces likelihood, and acceptance acknowledges the risk.",
  },
  {
    id: "spm_003", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A healthcare organization discovers employees are transmitting patient data via personal email. Which policy violation is this?",
    answers: [
      { id: "a", text: "Acceptable use policy", isCorrect: true },
      { id: "b", text: "Change management policy", isCorrect: false },
      { id: "c", text: "Incident response policy", isCorrect: false },
      { id: "d", text: "Data retention policy", isCorrect: false },
    ],
    explanation: "An acceptable use policy defines how employees may use organizational resources. Using personal email for patient data violates this policy and potentially HIPAA regulations.",
  },
  {
    id: "spm_004", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A company is onboarding a cloud vendor with access to sensitive data. What should they require from the vendor to validate security controls?",
    answers: [
      { id: "a", text: "Non-disclosure agreement (NDA)", isCorrect: false },
      { id: "b", text: "SOC 2 Type II report", isCorrect: true },
      { id: "c", text: "Service level agreement (SLA)", isCorrect: false },
      { id: "d", text: "Memorandum of understanding", isCorrect: false },
    ],
    explanation: "A SOC 2 Type II report provides independent validation of a vendor's security controls over time. SLAs cover performance, not controls. NDAs protect confidentiality but do not verify security.",
  },
  {
    id: "spm_005", type: "mcq", domain: "Security Program Management and Oversight",
    text: "An organization's security policy requires annual security awareness training. A manager asks why training is needed when technical controls exist. Which response BEST justifies the training?",
    answers: [
      { id: "a", text: "Training reduces the need for technical controls", isCorrect: false },
      { id: "b", text: "Humans are the most targeted attack surface", isCorrect: true },
      { id: "c", text: "Regulators require it regardless", isCorrect: false },
      { id: "d", text: "Training reduces insurance premiums", isCorrect: false },
    ],
    explanation: "Technical controls cannot prevent users from falling for phishing, tailgating, or mishandling data. Security awareness training addresses the human layer that no technical control can fully protect.",
  },
  {
    id: "spm_006", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which framework is specifically focused on providing a risk-based approach to cybersecurity for critical infrastructure?",
    answers: [
      { id: "a", text: "PCI DSS", isCorrect: false },
      { id: "b", text: "NIST Cybersecurity Framework", isCorrect: true },
      { id: "c", text: "HIPAA", isCorrect: false },
      { id: "d", text: "GDPR", isCorrect: false },
    ],
    explanation: "The NIST Cybersecurity Framework provides a risk-based approach for critical infrastructure. PCI DSS covers payment card data, HIPAA covers healthcare, and GDPR covers privacy.",
  },
  {
    id: "spm_007", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A CISO wants to verify that security controls operate as required by policy and that gaps are corrected. Which combination of actions BEST meets this need?",
    answers: [
      { id: "a", text: "Recurring internal audits and a finding register", isCorrect: true },
      { id: "b", text: "Annual penetration tests", isCorrect: false },
      { id: "c", text: "Quarterly vulnerability scans", isCorrect: false },
      { id: "d", text: "Security awareness training", isCorrect: false },
    ],
    explanation: "Internal audits verify control effectiveness, and a finding register tracks remediation. Penetration tests and scans are point-in-time and do not provide ongoing assurance.",
  },
  {
    id: "spm_008", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which of the following BEST describes the purpose of a business continuity plan (BCP)?",
    answers: [
      { id: "a", text: "Restore IT systems after a disaster", isCorrect: false },
      { id: "b", text: "Maintain critical business functions during disruption", isCorrect: true },
      { id: "c", text: "Transfer risk to an insurance provider", isCorrect: false },
      { id: "d", text: "Document security incident procedures", isCorrect: false },
    ],
    explanation: "A BCP focuses on maintaining business operations during disruption. Disaster recovery (DRP) focuses on restoring IT systems. Risk transfer is about insurance, and IRPs cover incident response.",
  },
  {
    id: "spm_009", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which metric represents the maximum amount of data loss an organization can tolerate in a disaster?",
    answers: [
      { id: "a", text: "RTO (Recovery Time Objective)", isCorrect: false },
      { id: "b", text: "RPO (Recovery Point Objective)", isCorrect: true },
      { id: "c", text: "MTBF (Mean Time Between Failures)", isCorrect: false },
      { id: "d", text: "MTTR (Mean Time to Repair)", isCorrect: false },
    ],
    explanation: "RPO defines the maximum acceptable data loss measured in time. RTO defines the maximum acceptable downtime. MTBF measures reliability, and MTTR measures restoration time.",
  },
  {
    id: "spm_010", type: "mcq", domain: "Security Program Management and Oversight",
    text: "An organization's security policy must comply with GDPR requirements. Which data subject right is guaranteed under GDPR?",
    answers: [
      { id: "a", text: "Right to unlimited data storage", isCorrect: false },
      { id: "b", text: "Right to erasure (right to be forgotten)", isCorrect: true },
      { id: "c", text: "Right to bypass security controls", isCorrect: false },
      { id: "d", text: "Right to access all company data", isCorrect: false },
    ],
    explanation: "GDPR grants data subjects the right to erasure (right to be forgotten), allowing them to request deletion of their personal data. Other rights include access, rectification, and portability.",
  },
  {
    id: "spm_011", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which of the following is a key element of a data governance program?",
    answers: [
      { id: "a", text: "Firewall configuration", isCorrect: false },
      { id: "b", text: "Data classification and handling procedures", isCorrect: true },
      { id: "c", text: "Intrusion detection rules", isCorrect: false },
      { id: "d", text: "Load balancing algorithms", isCorrect: false },
    ],
    explanation: "Data governance includes classifying data by sensitivity and defining how it should be handled, stored, and transmitted. Technical controls like firewalls are implementation tools, not governance elements.",
  },
  {
    id: "spm_012", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A company decides not to implement a security control because the cost exceeds the potential loss. Which risk response is this?",
    answers: [
      { id: "a", text: "Risk avoidance", isCorrect: false },
      { id: "b", text: "Risk acceptance", isCorrect: true },
      { id: "c", text: "Risk mitigation", isCorrect: false },
      { id: "d", text: "Risk transference", isCorrect: false },
    ],
    explanation: "Risk acceptance means acknowledging the risk and choosing not to act because the cost of mitigation exceeds the potential loss. Avoidance eliminates the activity entirely.",
  },
  {
    id: "spm_013", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which document defines the terms and conditions for a penetration testing engagement?",
    answers: [
      { id: "a", text: "Rules of engagement", isCorrect: true },
      { id: "b", text: "Service level agreement", isCorrect: false },
      { id: "c", text: "Business continuity plan", isCorrect: false },
      { id: "d", text: "Incident response plan", isCorrect: false },
    ],
    explanation: "Rules of engagement define the scope, boundaries, and terms for penetration testing, including what systems may be tested and what techniques are allowed.",
  },
  {
    id: "spm_014", type: "mcq", domain: "Security Program Management and Oversight",
    text: "An organization wants to reduce vendor risk when working with third-party suppliers. Which process is MOST effective?",
    answers: [
      { id: "a", text: "Annual security awareness training", isCorrect: false },
      { id: "b", text: "Vendor risk assessments and reviews", isCorrect: true },
      { id: "c", text: "Internal network segmentation", isCorrect: false },
      { id: "d", text: "Employee background checks", isCorrect: false },
    ],
    explanation: "Vendor risk assessments evaluate the security posture of third parties. Training and background checks address internal risk, and segmentation limits damage but does not assess vendor security.",
  },
  {
    id: "spm_015", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which of the following is the BEST example of a managerial security control?",
    answers: [
      { id: "a", text: "Firewall rule set", isCorrect: false },
      { id: "b", text: "Security policy document", isCorrect: true },
      { id: "c", text: "Badge reader at the entrance", isCorrect: false },
      { id: "d", text: "Intrusion detection system", isCorrect: false },
    ],
    explanation: "Security policies are managerial controls because they define rules and expectations. Firewalls and badge readers are technical/physical controls, and IDS is a technical detective control.",
  },
  {
    id: "spm_016", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A security team identifies that a system has a vulnerability with a CVSS score of 9.8. What does this score indicate?",
    answers: [
      { id: "a", text: "Low severity vulnerability", isCorrect: false },
      { id: "b", text: "Medium severity vulnerability", isCorrect: false },
      { id: "c", text: "Critical severity vulnerability", isCorrect: true },
      { id: "d", text: "Informational finding", isCorrect: false },
    ],
    explanation: "CVSS scores range from 0-10. A score of 9.8 is considered critical (9.0-10.0). Critical vulnerabilities should be prioritized for immediate remediation.",
  },
  {
    id: "spm_017", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which compliance framework specifically governs the handling of credit card payment information?",
    answers: [
      { id: "a", text: "HIPAA", isCorrect: false },
      { id: "b", text: "PCI DSS", isCorrect: true },
      { id: "c", text: "SOX", isCorrect: false },
      { id: "d", text: "FERPA", isCorrect: false },
    ],
    explanation: "PCI DSS (Payment Card Industry Data Security Standard) governs how organizations handle credit cardholder data. HIPAA covers healthcare, SOX covers financial reporting, and FERPA covers education records.",
  },
  {
    id: "spm_018", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A company wants to ensure that conflicting duties are split among different employees. Which principle is this?",
    answers: [
      { id: "a", text: "Least privilege", isCorrect: false },
      { id: "b", text: "Separation of duties", isCorrect: true },
      { id: "c", text: "Need to know", isCorrect: false },
      { id: "d", text: "Job rotation", isCorrect: false },
    ],
    explanation: "Separation of duties divides critical tasks among multiple people to prevent fraud or error. Least privilege limits permissions, need to know restricts data access, and job rotation cross-trains staff.",
  },
  {
    id: "spm_019", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which of the following is the PRIMARY purpose of a data retention policy?",
    answers: [
      { id: "a", text: "Ensure data is backed up daily", isCorrect: false },
      { id: "b", text: "Define how long data must be kept and when to delete it", isCorrect: true },
      { id: "c", text: "Encrypt all sensitive data", isCorrect: false },
      { id: "d", text: "Control who can access data", isCorrect: false },
    ],
    explanation: "A data retention policy specifies how long different types of data must be preserved and when they should be securely destroyed. Backup frequency and encryption are technical implementations.",
  },
  {
    id: "spm_020", type: "mcq", domain: "Security Program Management and Oversight",
    text: "During a risk assessment, a team identifies that a legacy system cannot be patched and no replacement is available. Which risk strategy is MOST appropriate?",
    answers: [
      { id: "a", text: "Risk avoidance", isCorrect: false },
      { id: "b", text: "Risk mitigation with compensating controls", isCorrect: true },
      { id: "c", text: "Risk ignorance", isCorrect: false },
      { id: "d", text: "Risk elimination", isCorrect: false },
    ],
    explanation: "When a vulnerability cannot be patched, compensating controls (such as network segmentation or strict access controls) can reduce the risk to an acceptable level.",
  },
  {
    id: "spm_021", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which of the following is a key difference between a policy and a procedure?",
    answers: [
      { id: "a", text: "Policies are technical, procedures are managerial", isCorrect: false },
      { id: "b", text: "Policies define what must be done, procedures define how", isCorrect: true },
      { id: "c", text: "Procedures are more important than policies", isCorrect: false },
      { id: "d", text: "Policies require annual approval, procedures do not", isCorrect: false },
    ],
    explanation: "Policies are high-level statements of management intent (what must be done). Procedures are detailed step-by-step instructions (how to do it). Both are important elements of governance.",
  },
  {
    id: "spm_022", type: "mcq", domain: "Security Program Management and Oversight",
    text: "An organization's disaster recovery plan specifies a two-hour RTO for a critical application. What does this mean?",
    answers: [
      { id: "a", text: "Up to two hours of data may be lost", isCorrect: false },
      { id: "b", text: "The application must be restored within two hours", isCorrect: true },
      { id: "c", text: "The application requires two hours of maintenance weekly", isCorrect: false },
      { id: "d", text: "Two hours of testing is required monthly", isCorrect: false },
    ],
    explanation: "RTO (Recovery Time Objective) is the maximum acceptable downtime. A two-hour RTO means the application must be fully operational within two hours of a disruption.",
  },
  {
    id: "spm_023", type: "mcq", domain: "Security Program Management and Oversight",
    text: "Which of the following BEST describes a service level agreement (SLA)?",
    answers: [
      { id: "a", text: "A contract defining expected performance and uptime", isCorrect: true },
      { id: "b", text: "A security policy for employee conduct", isCorrect: false },
      { id: "c", text: "A technical standard for encryption", isCorrect: false },
      { id: "d", text: "A risk assessment methodology", isCorrect: false },
    ],
    explanation: "An SLA is a contract that defines expected service levels, such as uptime guarantees, response times, and penalties for non-compliance. It is not a security policy or technical standard.",
  },
  {
    id: "spm_024", type: "mcq", domain: "Security Program Management and Oversight",
    text: "A security team needs to report the overall security posture to executives. Which metric is MOST meaningful for this audience?",
    answers: [
      { id: "a", text: "Number of firewall rules configured", isCorrect: false },
      { id: "b", text: "Risk assessment scores and remediation progress", isCorrect: true },
      { id: "c", text: "Average patch deployment time", isCorrect: false },
      { id: "d", text: "Number of IDS signatures updated", isCorrect: false },
    ],
    explanation: "Executive leadership needs risk-based metrics that show overall posture and progress. Technical details like patch time or signature counts are operational metrics for technical teams.",
  },
]
